[build]
  command = "CI='' yarn build"
  publish="build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[context.production.environment]
  REACT_APP_WEATHER_FORECASTER_API_KEY = "From netlify.toml (REACT_APP_)"